// v23: published MongoDB content only; no demo titles or fake chapters.
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const small=s=>String(s).replace(/[a-z]/gi,c=>({a:'ᴀ',b:'ʙ',c:'ᴄ',d:'ᴅ',e:'ᴇ',f:'ғ',g:'ɢ',h:'ʜ',i:'ɪ',j:'ᴊ',k:'ᴋ',l:'ʟ',m:'ᴍ',n:'ɴ',o:'ᴏ',p:'ᴘ',q:'ǫ',r:'ʀ',s:'s',t:'ᴛ',u:'ᴜ',v:'ᴠ',w:'ᴡ',x:'x',y:'ʏ',z:'ᴢ'}[c.toLowerCase()]||c));
const names={manga:'Manga',manhwa:'Manhwa',webtoon:'Webtoon',manhua:'Manhua',adult_manga:'18+ Manga',adult_manhwa:'18+ Manhwa',adult_webtoon:'18+ Webtoon'};
let state={page:1,filter:'',query:'',user:null,items:[],loading:false};
const cover=x=>x.cover_url?`<img loading="lazy" src="${esc(x.cover_url)}" alt="">`:'<span class="cover-placeholder">MIKO</span>';
function card(x){const fresh=x.updated_at&&Date.now()-Date.parse(x.updated_at)<86400000;return `<a class="card" href="#/title/${esc(x.category)}/${encodeURIComponent(x.slug)}"><div class="cover">${cover(x)}${fresh?'<span class="new-label">NEW</span>':''}</div><div class="card-info"><h3>${esc(x.title)}</h3><div class="meta">${small(names[x.category]||x.category)} · ${x.chapters?.length||0} ${small('chapters')}</div></div></a>`}
async function api(path,opts){
 let r;
 try { r=await fetch('/api/'+path,{credentials:'same-origin',...opts}); }
 catch(e){ throw Error(location.protocol==='http:'?'Secure connection required. Open the HTTPS website.':'Cannot reach the website API. Check HTTPS certificate and server status.'); }
 let d;
 try { d=await r.json(); } catch(e){ throw Error('Website API returned an invalid response (HTTP '+r.status+').'); }
 if(!r.ok)throw Error(d.error||'Request failed');return d;
}
function pager(total){if(total<=1)return '';return `<div class="pager"><button ${state.page<=1?'disabled':''} data-page="${state.page-1}">${small('Previous')}</button><b>${state.page} / ${total}</b><button ${state.page>=total?'disabled':''} data-page="${state.page+1}">${small('Next')}</button></div>`}
async function loadCatalog(){const route=location.hash.match(/^#\/category\/(manga|manhwa|manhua|webtoon|adult_manga|adult_manhwa|adult_webtoon)/);const category=route?route[1]:state.filter;const params=new URLSearchParams({page:state.page,q:state.query});if(category)params.set('category',category);const target=route?$('routePage'):$('cards');target.innerHTML='<p class="catalog-state">'+small('Loading published stories...')+'</p>';try{const data=await api('catalog?'+params);state.items=data.items;const cards=data.items.map(card).join('')||`<div class="catalog-state">${small('No published stories yet.')}</div>`;if(route){target.innerHTML=`<div class="page-breadcrumb"><a href="#/">${small('Home')}</a> / ${small(names[category])}</div><div class="listing-heading"><h1>${small(names[category])}</h1><span>${data.total} ${small('stories')}</span></div><div class="cards category-cards">${cards}</div>${pager(data.pages)}`}else{target.innerHTML=cards;$('resultCount').textContent=data.total+' '+small('published titles');$('catalogPager').innerHTML=pager(data.pages)}document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;loadCatalog();window.scrollTo({top:0,behavior:'smooth'})})}catch(e){target.innerHTML='<p class="catalog-state">'+small('Catalog temporarily unavailable. Please try again later.')+'</p>';if(!route)$('catalogPager').innerHTML=''}}
async function titlePage(cat,slug){$('routePage').innerHTML='<p class="catalog-state">'+small('Loading...')+'</p>';try{const x=await api('title?category='+cat+'&slug='+encodeURIComponent(slug));if(!x){$('routePage').innerHTML='<p class="catalog-state">'+small('Title not found on this page.')+'</p>';return}const chapters=(x.chapters||[]).map(ch=>`<div class="chapter"><b>${small('Chapter')} ${esc(ch.number)}</b><span>${small('Published')}</span></div>`).join('');$('routePage').innerHTML=`<div class="page-breadcrumb"><a href="#/">${small('Home')}</a> / <a href="#/category/${cat}">${small(names[cat])}</a></div><div class="detail-hero"><div class="detail-poster cover">${cover(x)}</div><div class="detail-info"><span class="kicker">${small(names[cat])}</span><h1>${esc(x.title)}</h1><h3>${small('Synopsis')}</h3><p>${esc(x.description||'')}</p></div></div><div class="listing-heading"><h2>${small('Chapter list')}</h2><span>${x.chapters?.length||0}</span></div><div class="chapter-list">${chapters}</div><p class="catalog-state">${small('Online chapter reader is being connected to Telegram storage.')}</p>`}catch(e){$('routePage').innerHTML='<p class="catalog-state">'+small('Unable to load story.')+'</p>'}}
function route(){let h=decodeURIComponent(location.hash||'#/');const cat=h.match(/^#\/category\/(manga|manhwa|manhua|webtoon|adult_manga|adult_manhwa|adult_webtoon)/),title=h.match(/^#\/title\/(manga|manhwa|manhua|webtoon|adult_manga|adult_manhwa|adult_webtoon)\/(.+)$/);const auth=h.match(/^#\/auth\/(login|signup)$/),profile=h==='#/profile';const home=!cat&&!title&&!auth&&!profile;$('homeContent').hidden=!home;$('routePage').hidden=home;$('nav').classList.remove('open');$('menuBtn').setAttribute('aria-expanded','false');state.page=1;if(auth)authPage(auth[1]);else if(profile)profilePage();else if(title)titlePage(title[1],title[2]);else loadCatalog();if(!home)window.scrollTo(0,0)}
$('menuBtn').onclick=()=>{let open=$('nav').classList.toggle('open');$('menuBtn').setAttribute('aria-expanded',String(open))};
document.querySelectorAll('.category[data-filter]').forEach(b=>b.onclick=()=>location.hash='#/category/'+(b.dataset.filter.toLowerCase()));
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter==='All'?'':b.dataset.filter.toLowerCase();state.page=1;document.querySelectorAll('.filter').forEach(z=>z.classList.toggle('selected',z===b));loadCatalog()});
$('searchInput').oninput=e=>{state.query=e.target.value;state.page=1;clearTimeout(window.searchTimer);window.searchTimer=setTimeout(loadCatalog,350)};
$('searchToggle').onclick=()=>{location.hash='#/';$('searchInput').focus();$('library').scrollIntoView({behavior:'smooth'})};
function modal(content){$('modalBody').innerHTML=content;$('overlay').hidden=false}
$('closeModal').onclick=()=>{$('overlay').hidden=true};$('overlay').onclick=e=>{if(e.target===$('overlay'))$('overlay').hidden=true};
async function refreshUser(){try{state.user=(await api('me')).user}catch(e){state.user=null}let b=$('adminBtn');b.textContent=state.user?small('Profile'):small('Sign in');b.title=state.user?.email||'Sign in';$('accountNav').href=state.user?'#/profile':'#/auth/login';$('accountNav').textContent=small(state.user?'My profile':'Sign in / Sign up')}
function authPage(mode){
 const signup=mode==='signup';
 const passwordField=(name,label,auto)=>`<label class="auth-label" for="auth-${name}">${small(label)}</label><div class="password-wrap"><input id="auth-${name}" name="${name}" type="password" minlength="8" maxlength="128" autocomplete="${auto}" required><button class="password-toggle" type="button" data-for="auth-${name}" aria-label="Show password" aria-pressed="false" title="Show password"><svg viewBox="0 0 24 24" width="23" height="23" aria-hidden="true"><path d="M2 12s3.7-6 10-6 10 6 10 6-3.7 6-10 6S2 12 2 12Z" fill="none" stroke="currentColor" stroke-width="1.8"/><circle cx="12" cy="12" r="3" fill="none" stroke="currentColor" stroke-width="1.8"/></svg></button></div>`;
 $('routePage').innerHTML=`<section class="account-page"><a href="#/" class="account-back">${small('Back to home')}</a><div class="account-panel"><span class="kicker">${small('MIKO ACCOUNT')}</span><h1>${signup?'Create Account':'Sign In'}</h1><p class="auth-intro">${small(signup?'Create your reading account.':'Welcome back. Continue reading.')}</p><form id="authPageForm" class="auth-form"><label class="auth-label" for="auth-email">${small('Email address')}</label><input id="auth-email" name="email" type="email" autocomplete="email" required maxlength="254">${passwordField('password','Password',signup?'new-password':'current-password')}${signup?passwordField('confirm','Confirm password','new-password'):''}${signup?`<p class="auth-hint">${small('8-128 characters, including 1 number and 1 special character.')}</p>`:''}<button type="submit" class="primary">${small(signup?'Create account':'Sign in')}</button><p id="authFeedback" role="status" aria-live="polite"></p></form><p class="account-switch">${small(signup?'Already have an account?':'New to MIKO?')} <a href="#/auth/${signup?'login':'signup'}">${small(signup?'Sign in':'Create account')}</a></p></div></section>`;
 document.querySelectorAll('.password-toggle').forEach(btn=>btn.onclick=()=>{const el=$(btn.dataset.for);const showing=el.type==='password';el.type=showing?'text':'password';btn.classList.toggle('visible',showing);btn.title=showing?'Hide password':'Show password';btn.setAttribute('aria-label',showing?'Hide password':'Show password');btn.setAttribute('aria-pressed',String(showing));});
 $('authPageForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const email=f.get('email'),password=f.get('password');const feedback=$('authFeedback');if(signup){if(!/^(?=.{8,128}$)(?=.*[0-9])(?=.*[^A-Za-z0-9\s])[^\s]+$/.test(password)){feedback.textContent=small('Use 8-128 characters, including a number and a special character.');return}if(password!==f.get('confirm')){feedback.textContent=small('Passwords do not match.');return}}const submit=e.target.querySelector('[type=submit]');submit.disabled=true;try{await api(signup?'register':'login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});if(signup){location.hash='#/auth/login';setTimeout(()=>{const el=$('authFeedback');if(el)el.textContent=small('Account created. Please sign in.')},0)}else{await refreshUser();location.hash='#/profile'}}catch(err){feedback.textContent=err.message}finally{submit.disabled=false}};
}

function profilePage(){if(!state.user){location.hash='#/auth/login';return}const isOwner=state.user.role==='owner';$('routePage').innerHTML=`<section class="account-page"><a href="#/" class="account-back">${small('Back to home')}</a><div class="account-panel"><span class="kicker">${small('My account')}</span><h1>${small('Profile')}</h1><p><b>${small('Email')}:</b> ${esc(state.user.email)}</p><p><b>${small('Role')}:</b> ${small(state.user.role)}</p>${isOwner?`<div class="owner-note"><b>${small('Owner access verified')}</b><p>${small('Administration features will appear here when publishing controls are enabled.')}</p></div>`:''}<button id="profileLogout" class="primary">${small('Log out')}</button></div></section>`;$('profileLogout').onclick=async()=>{await api('logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refreshUser();location.hash='#/auth/login'};}
$('adminBtn').onclick=()=>{location.hash=state.user?'#/profile':'#/auth/login'};
window.addEventListener('hashchange',route);refreshUser().then(()=>{if(location.hash==='#/profile')route()});route();
